webapp/website/views.py
from unittest import result
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .models import Note
from . import db
import json
from .account_utils import *
import os
from flask import Flask, request, render_template, send_from_directory
from .counter_utils import *
from .record_utils import record_intake,get_past_intake_days

views = Blueprint('views', __name__)
APP_ROOT = os.path.dirname(os.path.abspath(__file__))

@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')

    return redirect(url_for("views.dashboard"))
    #return render_template("home.html", user=current_user)


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

@views.route("/dashboard.html")
@login_required
def dashboard():
    return render_template('index.html',name=current_user.email) 


@views.route("/settings.html")
@login_required
def settings():
    current_settings=get_settings(current_user.id)["data"]
    print(current_settings.items())
    return render_template('settings.html',current_settings=current_settings.items(),name=current_user.email)

@views.route("/change_settings", methods=['POST'])
@login_required
def change_settings():
    user_id=current_user.id
    new_setting={"user_id":user_id}
    #print(request.form)
    # for i in survey_options:
    #     new_setting[i]=request.form.get(i)=="on"
    #print(new_setting)
    update_settings(current_user.id,new_setting)

    return redirect(url_for("views.settings"))

@views.route("/records.html")
@login_required
def tracking():
    return render_template('records.html',name=current_user.email)

@views.route("/analysis.html")
@login_required
def analysis():
    return render_template('analysis.html',name=current_user.email)

@views.route("/upload.html")
@login_required
def index():
    return render_template("upload.html",name=current_user.email)

@views.route("/upload", methods=["POST"])
@login_required
def upload(): # allowed user upload multiple files
    target = os.path.join(APP_ROOT, 'scanned_images/')
    print(target)

    if not os.path.isdir(target):
        os.mkdir(target)

    for file in request.files.getlist("file"):
        print(file)
        filename = file.filename
        destination = "/".join([target, filename])
        print(destination)
        file.save(destination)
    return render_template("analysis.html",name=current_user.email)

@views.route("/scan", methods=["POST"])
@login_required
def scan():
    filename = os.path.join(APP_ROOT, 'scanned_images/', request.form['file_name'])
    # return jsonify(response=filename)#process_image(filename))
    # results = process_image(filename)
    results = filename
    return render_template("analysis.html",name=current_user.email,results=results)


@views.route("/help.html")
@login_required
def help():
    return render_template('help.html',name=current_user.email)

@views.route("/profile.html")
@login_required
def profile():
    return redirect(url_for("views.settings"))

@views.route("/admin")
@login_required
def admin():
    return redirect(url_for("home"))

@login_required
@views.route("/records/get_analysis",methods=['POST'])
def get_analysis():
    my_request=request.json
    print(current_user.id,str(my_request["day"]),my_request["date"])
    print(get_past_intake_days(current_user.id,str(my_request["day"]),end_date=my_request["date"]))
    return get_past_intake_days(current_user.id,str(my_request["day"]),end_date=my_request["date"])

#This method also input record into user's database
@login_required
@views.route("/records/get_records",methods=['POST'])
def get_records():
    my_request=request.json
    print(my_request, current_user.id)
    print(str(my_request['location']),
        str(my_request['name']),
        str(my_request['result']))
    # response= nutrition_utils.get_nutrition(str(my_request['foodId']),str(my_request['measure']),int(my_request['quantity']))
    
    record_intake(
        current_user.id,
        str(my_request['location']),
        str(my_request['name']),
        str(my_request['result'])
    )
    return request

webapp/website/templates/analysis.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="{{ url_for('static', filename='img/icons/icon-48x48.png') }}" />

	<link rel="canonical" href="https://demo-basic.adminkit.io/" />

	<title>Analysis | Sensitive Droplet Sensing</title>

	<link id="mystylesheet", href="static/css/app.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<body>
	<div class="wrapper">
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
					<a class="sidebar-brand" href="index.html">
          <span class="align-middle">Sensitive Droplet Sensing</span>
        </a>

				<ul class="sidebar-nav">
					<li class="sidebar-header">
						Pages
					</li>

					<li class="sidebar-item">
                        <a class="sidebar-link" href="index.html">
                            <i class="align-middle" data-feather="home"></i> <span class="align-middle">Home</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="analysis.html">
                            <i class="align-middle" data-feather="activity"></i> <span class="align-middle">Analysis</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="records.html">
                            <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Records</span>
                        </a>
                    </li>
			</nav>
			<div class="main">
				<nav class="navbar navbar-expand navbar-light navbar-bg">
					<a class="sidebar-toggle js-sidebar-toggle">
          		<i class="hamburger align-self-center"></i>
       		 </a>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav navbar-align">				
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
                <i class="align-middle" data-feather="settings"></i>
              </a>

							<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                <img src="{% if name %}{{ url_for('static', filename='img/avatars/avatar.jpg') }}{% else %}{{url_for('static', filename='img/avatars/undefined.png')}}{% endif %}" class="avatar img-fluid rounded me-1" alt="Charles Hall" /> <span class="text-dark">{% if name %}{{name}}{% else %}unregistered{% endif %}</span>
              </a>
							<div class="dropdown-menu dropdown-menu-end">
								<a class="dropdown-item" href="profile.html"><i class="align-middle me-1" data-feather="user"></i> Settings</a>
								<a class="dropdown-item" href="help.html"><i class="align-middle me-1" data-feather="help-circle"></i> Help Center</a>
								<button class="btn" onclick="swapStyles('/static/css/dark.css')"><i data-feather="moon"></i></button>
								<button class="btn" onclick="swapStyles('static/css/app.css')"><i data-feather="sun"></i></button>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="logout">Log out</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>

			<main class="content">
				<div class="container-fluid p-0">

					<h1 class="h3 mb-3"><strong>Analysis</strong></h1>

				<div class="card">
					<div class="card-body">
						<body>
							<form id="upload-form" action="{{ url_for('views.upload') }}" method="POST" enctype="multipart/form-data">
								<h4 class="text-muted"><strong>
									Upload your images here, please remember the name of your file:
								</strong></h4>
								<br><br>
								<input id="file-picker" type="file" name="file" accept="image/*" multiple>
								<div id="msg"></div>
								<br><br>
								<input type="submit" value="Upload" id="upload-button">
							</form>
						</body>
					</div>
				</div>

				<div class="card">
					<div class="card-body">
						<body>
							<h4 class="text-muted"><strong>
								After upload your images, input the name of your file and click the button below to process the image:
							</strong></h4>
							<div class="col-7">
								<form id="scan-form" action="{{ url_for('views.scan') }}" method="POST" enctype="multipart/form-data">
									<strong>Uploaded file name:</strong>
									<input class="mx-auto" type="text" name="file_name">
									<br><br>
									<input type="submit" value="Scan" id="scan-button">
								</form>
							</div>
						</body>
					</div>
				</div>

				<div class="card">
					<div class="card-body">
						<body>
							<h1 class="h3 mb-3"><strong>Result</strong></h1>
							<!-- <p>The scan result is <strong>Positive</strong><br><br><br><br><br><br><br><br><br></p> -->
							<!-- <p>{{results}}</p> -->
							<!-- <picture><img src='../../website/scanned_images/dots.png'/></picture> -->
							
						</body>
					</div>
				</div>
				
				</div>
			</main>

			<footer class="footer">
				<div class="container-fluid">
					<div class="row text-muted">
						<div class="col-6 text-start">
							<p class="mb-0">
								<a class="text-muted" href="https://adminkit.io/" target="_blank"><strong>Sensitive Droplet Sensing</strong></a> &copy;
							</p>
						</div>
					</div>
				</div>
			</footer>
		</div>
	</div>

	<script src="{{ url_for('static', filename='js/app.js') }}"></script>

	<script>
		// used for get the avariables

		function submit_form(form_data,server_url){
			form_response={}
			var xhr = new XMLHttpRequest();
			xhr.open("POST", server_url,false);
			xhr.onload = function(event){ 
				//alert("Success, server responded with: " + event.target.response); // raw response
				//document.getElementById("auto_complete_list") 
				//console.log(event.target.response);
				form_response=JSON.parse(event.target.response);
			}; 
			// or onerror, onabort
			xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
			xhr.send(JSON.stringify(form_data));
			return form_response;
		}

		document.onreadystatechange = async function () {
		  if (document.readyState == "complete") {
			pass
		  }
		}

	</script>
</body>

</html>

webapp/website/templates/help.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="{{ url_for('static', filename='img/icons/icon-48x48.png') }}" />

	<link rel="canonical" href="https://demo-basic.adminkit.io/" />

	<title>Sensitive Droplet Sensing - Sensitive Droplets Sensing Platform</title>

	<link id="mystylesheet", href="static/css/app.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<body>
	<div class="wrapper">
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
				<a class="sidebar-brand" href="index.html">
          <span class="align-middle">Sensitive Droplet Sensing</span>
        </a>

				<ul class="sidebar-nav">
					<li class="sidebar-header">
						Pages
					</li>

					<li class="sidebar-item">
                        <a class="sidebar-link" href="index.html">
                            <i class="align-middle" data-feather="home"></i> <span class="align-middle">Home</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="analysis.html">
                            <i class="align-middle" data-feather="activity"></i> <span class="align-middle">Analysis</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="records.html">
                            <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Records</span>
                        </a>
                    </li>
		</nav>

		<div class="main">
			<nav class="navbar navbar-expand navbar-light navbar-bg">
				<a class="sidebar-toggle js-sidebar-toggle">
          <i class="hamburger align-self-center"></i>
        </a>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav navbar-align">
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
                <i class="align-middle" data-feather="settings"></i>
              </a>

							<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                <img src="{% if name %}{{ url_for('static', filename='img/avatars/avatar.jpg') }}{% else %}{{url_for('static', filename='img/avatars/undefined.png')}}{% endif %}" class="avatar img-fluid rounded me-1" alt="Charles Hall" /> <span class="text-dark">{% if name %}{{name}}{% else %}unregistered{% endif %}</span>
              </a>
							<div class="dropdown-menu dropdown-menu-end">
								<a class="dropdown-item" href="profile.html"><i class="align-middle me-1" data-feather="user"></i> Settings</a>
								<a class="dropdown-item" href="help.html"><i class="align-middle me-1" data-feather="help-circle"></i> Help Center</a>
								<button class="btn" onclick="swapStyles('/static/css/dark.css')"><i data-feather="moon"></i></button>
								<button class="btn" onclick="swapStyles('static/css/app.css')"><i data-feather="sun"></i></button>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="logout">Log out</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>

			<main class="content">
			  <div class="container-fluid p-0">
				<h1 class="h3 mb-3"><strong>Need help, you're at the right place!</strong></h1>
				<div class="row">
				  <div class="card col-xl-6 d-flex">
					<h1 class="display-6"><strong>FAQ's</strong></h1>
				<h3 class="mt-1 mb-3"><strong>How does Sensitive Droplet Sensing work?</strong></h3>
				<h2 class="card-title"><em>
					placeholder				
				</em></h2>
				<h3 class="mt-1 mb-3"><strong>Who are we?</strong></h3>
				<h2 class="card-title"><em>
					placeholder
				</em></h2>
				<h3 class="mt-1 mb-3"><strong>What is Innovation-X?</strong></h3>
				<h2 class="card-title"><em>
					placeholder
				</em></h2>
				<h3 class="mt-1 mb-3"><strong>xyz?</strong></h3>
				<h2 class="card-title"><em>
					placeholder
				</em></h2>
			  </div>

				  
				  <div class="col-sm-6">

					<div class="card">
					  <div class="card-body">
						<div class="row">
						  <div class="col mt-0">
							<h1 class="font-weight-bold"><strong>How to use the mobile app?</strong></h1>
						  </div>
						  <div class="col-auto">
							<div class="stat text-primary">
							  <i class="align-middle" data-feather="edit"></i>
							</div>
						  </div>
						  </div>
						    <h4 class="text-muted"><em>
								placeholder
							</em></h4>
							<h4 class="text-muted"><strong><em>
								Check out our demo here. (link the video if we have later)
								<!-- <a href="tracking.html">here.</a> -->
							</em></strong></h4>
						  </div>
					</div>

					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col mt-0">
								  <h1 class="font-weight-bold"><strong>How to use this website?</strong></h1>
								</div>
								<div class="col-auto">
								  <div class="stat text-primary">
									<i class="align-middle" data-feather="bar-chart"></i>
								  </div>
								</div>
							</div>
							<h4 class="text-muted"><em>
								placeholder
							</em></h4>
							<h4 class="text-muted"><strong><em>
								Try the analysis function by clicking 
								<a href="analysis.html">here.</a>
							</em></strong></h4>
						</div>
					</div>

				  </div>

				</div>
			</main>

			<footer class="footer">
				<div class="container-fluid">
					<div class="row text-muted">
						<div class="col-6 text-start">
							<p class="mb-0">
								<a class="text-muted" href="https://adminkit.io/" target="_blank"><strong>Sensitive Droplet Sensing</strong></a> &copy;
							</p>
						</div>
					</div>
				</div>
			</footer>
		</div>
	</div>

	<script src="{{ url_for('static', filename='js/app.js') }}"></script>

	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var ctx = document.getElementById("chartjs-dashboard-line").getContext("2d");
			var gradient = ctx.createLinearGradient(0, 0, 0, 225);
			gradient.addColorStop(0, "rgba(215, 227, 244, 1)");
			gradient.addColorStop(1, "rgba(215, 227, 244, 0)");
			// Line chart
			new Chart(document.getElementById("chartjs-dashboard-line"), {
				type: "line",
				data: {
					labels: ["Sun", "Mon", "Tues", "Wed", "Thur", "Fri", "Sat"],
					datasets: [{
						label: "Sales ($)",
						fill: true,
						backgroundColor: gradient,
						borderColor: window.theme.primary,
						data: [
							2115,
							1562,
							1584,
							1892,
							1587,
							1923,
							2566
						]
					}]
				},
				options: {
					maintainAspectRatio: false,
					legend: {
						display: false
					},
					tooltips: {
						intersect: false
					},
					hover: {
						intersect: true
					},
					plugins: {
						filler: {
							propagate: false
						}
					},
					scales: {
						xAxes: [{
							reverse: true,
							gridLines: {
								color: "rgba(0,0,0,0.0)"
							}
						}],
						yAxes: [{
							ticks: {
								stepSize: 1000
							},
							display: true,
							borderDash: [3, 3],
							gridLines: {
								color: "rgba(0,0,0,0.0)"
							}
						}]
					}
				}
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			// Pie chart
			new Chart(document.getElementById("chartjs-dashboard-pie"), {
				type: "pie",
				data: {
					labels: ["Chrome", "Firefox", "IE"],
					datasets: [{
						data: [4306, 3801, 1689],
						backgroundColor: [
							window.theme.primary,
							window.theme.warning,
							window.theme.danger
						],
						borderWidth: 5
					}]
				},
				options: {
					responsive: !window.MSInputMethodContext,
					maintainAspectRatio: false,
					legend: {
						display: false
					},
					cutoutPercentage: 75
				}
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			// Bar chart
			new Chart(document.getElementById("chartjs-dashboard-bar"), {
				type: "bar",
				data: {
					labels: ["Calories", "Carbs", "Proteins", "Fats"],
					datasets: [{
						label: "Average",
						backgroundColor: window.theme.primary,
						borderColor: window.theme.primary,
						hoverBackgroundColor: window.theme.primary,
						hoverBorderColor: window.theme.primary,
						data: [1500, 700, 500, 300, 100],
						barPercentage: .75,
						categoryPercentage: .5
					}]
				},
				options: {
					maintainAspectRatio: false,
					legend: {
						display: false
					},
					scales: {
						yAxes: [{
							gridLines: {
								display: false
							},
							stacked: false,
							ticks: {
								stepSize: 20
							}
						}],
						xAxes: [{
							stacked: false,
							gridLines: {
								color: "transparent"
							}
						}]
					}
				}
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var markers = [{
					coords: [31.230391, 121.473701],
					name: "Shanghai"
				},
				{
					coords: [28.704060, 77.102493],
					name: "Delhi"
				},
				{
					coords: [6.524379, 3.379206],
					name: "Lagos"
				},
				{
					coords: [35.689487, 139.691711],
					name: "Tokyo"
				},
				{
					coords: [23.129110, 113.264381],
					name: "Guangzhou"
				},
				{
					coords: [40.7127837, -74.0059413],
					name: "New York"
				},
				{
					coords: [34.052235, -118.243683],
					name: "Los Angeles"
				},
				{
					coords: [41.878113, -87.629799],
					name: "Chicago"
				},
				{
					coords: [51.507351, -0.127758],
					name: "London"
				},
				{
					coords: [40.416775, -3.703790],
					name: "Madrid "
				}
			];
			var map = new jsVectorMap({
				map: "world",
				selector: "#world_map",
				zoomButtons: true,
				markers: markers,
				markerStyle: {
					initial: {
						r: 9,
						strokeWidth: 7,
						stokeOpacity: .4,
						fill: window.theme.primary
					},
					hover: {
						fill: window.theme.primary,
						stroke: window.theme.primary
					}
				},
				zoomOnScroll: false
			});
			window.addEventListener("resize", () => {
				map.updateSize();
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var date = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000);
			var defaultDate = date.getUTCFullYear() + "-" + (date.getUTCMonth() + 1) + "-" + date.getUTCDate();
			document.getElementById("datetimepicker-dashboard").flatpickr({
				inline: true,
				prevArrow: "<span title=\"Previous month\">&laquo;</span>",
				nextArrow: "<span title=\"Next month\">&raquo;</span>",
				defaultDate: defaultDate
			});
		});
	</script>
<script src="static/darkmode.js"></script>
</body>

</html>

webapp/website/templates/settings.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
    <meta name="author" content="AdminKit">
    <meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/icons/icon-48x48.png') }}" />

    <link rel="canonical" href="https://demo-basic.adminkit.io/profile.html" />

    <title>Settings| Sensitive Droplet Sensing</title>

    <link id="mystylesheet", href="static/css/app.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <nav id="sidebar" class="sidebar js-sidebar">
            <div class="sidebar-content js-simplebar">
                <a class="sidebar-brand" href="index.html">
          <span class="align-middle">Sensitive Droplet Sensing</span>
        </a>

                <ul class="sidebar-nav">
                    <li class="sidebar-header">
                        Pages
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="index.html">
                            <i class="align-middle" data-feather="home"></i> <span class="align-middle">Home</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="analysis.html">
                            <i class="align-middle" data-feather="activity"></i> <span class="align-middle">Analysis</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="records.html">
                            <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Records</span>
                        </a>
                    </li>



                    <!-- <li class="sidebar-item">
                        <a class="sidebar-link" href="recommendations.html">
              <i class="align-middle" data-feather="book"></i> <span class="align-middle">Recommendations</span>
            </a>
                    </li> -->
        </nav>

        <div class="main">
            <nav class="navbar navbar-expand navbar-light navbar-bg">
                <a class="sidebar-toggle js-sidebar-toggle">
          <i class="hamburger align-self-center"></i>
        </a>

                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav navbar-align">
                    
                        <li class="nav-item dropdown">
                            <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
                <i class="align-middle" data-feather="settings"></i>
              </a>

                            <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                <img src="{% if name %}{{ url_for('static', filename='img/avatars/avatar.jpg') }}{% else %}{{url_for('static', filename='img/avatars/undefined.png')}}{% endif %}" class="avatar img-fluid rounded me-1" alt="Charles Hall" /> <span class="text-dark">{% if name %}{{name}}{% else %}unregistered{% endif %}</span>
              </a>
                            <div class="dropdown-menu dropdown-menu-end">
					<a class="dropdown-item" href="profile.html"><i class="align-middle me-1" data-feather="user"></i> Settings</a>
					<a class="dropdown-item" href="help.html"><i class="align-middle me-1" data-feather="help-circle"></i> Help Center</a>
					<button class="btn" onclick="swapStyles('/static/css/dark.css')"><i data-feather="moon"></i></button>
					<button class="btn" onclick="swapStyles('static/css/app.css')"><i data-feather="sun"></i></button>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="logout">Log out</a>
				</div>
                        </li>
                    </ul>
                </div>
            </nav>

            <main class="content">
                <div class="container-fluid p-0">

                    <div class="mb-3">
                        <h1 class="h3 d-inline align-middle">Profile</h1>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-xl-3">
                            <div class="card mb-3">
                                <div class="card-header">
                                    <h5 class="card-title mb-0">Placeholder</h5>
                                </div>
                                <!-- <div class="card-body text-center">
                                    <style>
                                        tr { display: block; float: left; }
                                    th, td { display: block; border: 1px solid black; }

                                    /* border-collapse */
                                    tr>*:not(:first-child) { border-top: 0; }
                                    tr:not(:first-child)>* { border-left:0; }
                                    </style>
                                    <form action="/change_settings" method="POST">
                                    <table>
                                    <tr>
                                        {% for k,v in current_settings %}
                                        <td style="padding:2.5px;">{{k}}</td>
                                        {% endfor %}
                                    </tr>
                                    <tr>
                                        {% for k,v in current_settings %}
                                        <td style="padding:2.5px;"><input type="checkbox" id="{{k}}" name="{{k}}" {%if v%}checked{% else %}{% endif %}></td>
                                        {% endfor %}
                                    </tr>
                                    </table>
                                    <div class="c-grid">
                                        <input href="#" class="btn btn-primary" type="submit" value="Submit">
                                    </div>
                                   </form> 
                                </div> -->
                            </div>
                        </div>
                    </div>

                </div>
            </main>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="row text-muted">
                        <div class="col-6 text-start">
                            <p class="mb-0">
                                <a class="text-muted" href="https://adminkit.io/" target="_blank"><strong>Sensitive Droplet Sensing</strong></a> &copy;
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
	<script src="static/darkmode.js"></script>

</body>

</html>